### ISSUE TITLE
r8152 usb LAN card not recognized

### ISSUE THREAD

**Issue by PangMo5** [fbelavenuto/arpl-modules#11]
Hello, first of all, thank you for creating a awesome tool.

Selected as ds920+, 42951

image version: [v0.4-alpha2](https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha2)

The model I use is `NEXT-2501GU3`.

What's unique is that when I access 7681 ports to set up the loader for the first time, I can use the LAN card to access them normally.

It is not recognized after boot after loader build.

**Comment by fbelavenuto** [comment]
Added non-free firmwares, please update modules, rebuild loader and test

**Comment by PangMo5** [comment]
After creating a new usb and updating the modules, the symptoms are still the same.

**Comment by fbelavenuto** [comment]
Ok, thanks for the test

**Comment by PangMo5** [comment]
Thanks!

**Comment by fbelavenuto** [comment]
My RTL8153 adapter works now with last version (v0.4-alpha12), please test with your adapter.

**Comment by PangMo5** [comment]
Unfortunately it still doesn't seem to work..

If the 8153 adapter was made to work because of [this PR](https://github.com/fbelavenuto/arpl/pull/194)
I guess my LAN card is not working because there is no fw related to 8152 in the PR. Is that right?

**Comment by PangMo5** [comment]
Is it correct that the `first partition` means `volume1`?
Anyway I accessed through ssh and checked all volume, but I couldn't find the logs folder.
I'll try again today as a whole.

**Comment by fbelavenuto** [comment]
Please, go to loader, update addons, recreate loader and test it again

**Comment by PangMo5** [comment]
It doesn't work.
Should I upload the logs file in the same way?

**Comment by fbelavenuto** [comment]
Please upload the new logs

**Comment by PangMo5** [comment]
[here](https://drive.google.com/file/d/1KZc4xKT2IfcrZf7eYNVKJffWijJz5Pcw/view?usp=sharing)

**Comment by PangMo5** [comment]
unfortunately it doesn't work :(
Thank you for continuing to try
I think it would be better to just buy another lan card.

**Comment by PangMo5** [comment]
unfortunately it doesn't work :(
Thank you for continuing to try

**Comment by PangMo5** [comment]
What seems to be the problem is that when I proceed without config modification, the mac1 shown in `cmdline:` is `d4~`, but the mac address on my lancard is `00~`. `d4~` is my mainboard's mac address, can this be a hint?

**Comment by fbelavenuto** [comment]
> can this be a hint?

Yes, I believe you have understood the problem now. Please type in the loader: "lspci -nnk"
In the loader are you using only the wifi card to download from the internet or are you using one of the onboard network cards?

**Comment by PangMo5** [comment]
> Please type in the loader: "lspci -nnk"
Can you explain this part in more detail?

> In the loader are you using only the wifi card to download from the internet or are you using one of the onboard network cards?

I making and using a new loader usb always without updating it within the loader.
And before dsm boots(in ip:7681), the usb LAN card works normally.
Therefore, I'm not using the onboard LAN and wifi modules.

**Comment by fbelavenuto** [comment]
Sorry, type into the prompt:

![image](https://user-images.githubusercontent.com/11461290/203071020-7a2ad31e-f555-45e4-915b-6666697d25bc.png)

**Comment by fbelavenuto** [comment]
Please update ARPL, reboot, update modules, addons and lkm, rebuild the loader and test it.
Try to de-select module "cdc-ncm", rebuild and test

**Comment by PangMo5** [comment]
I did as you said, but it didn't work properly.
But just in case, I replaced mac1 with a LAN card MAC address and de-select the "cdc-ncm" module, and it works fine!
The speed is good, too.

Thank you for taking care of me until the end.
