### ISSUE TITLE
Ixgbevf driver not found

### ISSUE THREAD

**Issue by hxlls** [fbelavenuto/arpl-modules#118]
hello, Previous versions have ixgbeVF network card drivers. Why is it removed from 1.0 beta9?

**Comment by hxlls** [comment]
I checked the source code and found that the ixgbevf driver was removed here, but I don't know why. The driver works normally in my tests.
[19469c70aeb7603332a0e47bfdcb5a94d9c05ecd](https://github.com/fbelavenuto/arpl-modules/commit/19469c70aeb7603332a0e47bfdcb5a94d9c05ecd)

**Comment by fbelavenuto** [comment]
Please update modules, rebuild loader and test again

**Comment by hxlls** [comment]
Tested and repaired
