### ISSUE TITLE
i350t4 not recognized

### ISSUE THREAD

**Issue by brg3466** [fbelavenuto/arpl-modules#12]
first , thank you for the great works !  I installed DS920+ under PVE on Lenovo P350SFF i9-11900.   It cannot recognize the i350t4 ( on PCIe expansion slot)  and cannot get the right cpu info.

**Comment by fbelavenuto** [comment]
Please update modules, rebuild the loader and test it

**Comment by brg3466** [comment]
Yes, it works !  Thank you so much !

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
