### ISSUE TITLE
hp AMS

### ISSUE THREAD

**Issue by lwd940724** [fbelavenuto/arpl-modules#121]
hi, can you increase the generation of HP AMS drivers? Many people use HP servers to install Synology. Without this driver, hardware parameters cannot be read in the background of HP ilo. Here is a link you can refer to. thank you very much 
https://xpenology.com/forum/topic/4242-hp-microserver-gen8-and-hp-ams/page/5/

**Comment by fbelavenuto** [comment]
Added, just update modules, rebuild the loader and test it
