### ISSUE TITLE
Can't connect with specific lan card

### ISSUE THREAD

**Issue by winiaa11090** [fbelavenuto/arpl-modules#13]
Hello. i had installed arpl 0.4 alpha 2

and it was succeeded with on board lan (RTL8111H)
But i found that can't connect with pcie lan (Emulex CX312A) and it can't to have ip address 

and i can't see device detecting alert on Loader . Or, is there any path to make Loader for serching and dectecing?

but something is weird. according to second image. In the power recovery option, it appears as if there are two LAN ports.

I had attached lspci -nnk so, please check it

lastly, my version is 7.1.0 - 42218 and device is 918+ 
cpu is J4105-ITX 
if there any information you need, i will coorperate quickly

thank you for your kindness

![image](https://user-images.githubusercontent.com/44671258/185207255-58506c98-42c4-4476-80b9-106dd48e0aa3.png)

![image](https://user-images.githubusercontent.com/44671258/185207314-f45de0be-8356-4fc9-92ed-aa47b15c882b.png)

**Comment by fbelavenuto** [comment]
For log: Driver source code:
https://download2.boulder.ibm.com/sar/CMA/XSA/07wel/0/brcm_dd_nic_17a-11.2.1193.91-1_rhel6_32-64.tgz

**Comment by winiaa11090** [comment]
M..may i ask you how to install it? 

 I'm really sorry to bother you...

**Comment by fbelavenuto** [comment]
I need to compile the driver to generate the binary. I put the link here for my reference, you don't need to do anything for now.
When I manage to compile and generate a new driver package, I'll let you know.

**Comment by winiaa11090** [comment]
Oh! Okay. I really glad to you address this situation!

**Comment by fbelavenuto** [comment]
I've added be2net module, please update modules, rebuild the loader and test.

**Comment by winiaa11090** [comment]
I can't believe your speed!
I had tested your work of adding, and it's going well even after the reboot. Now i can use my Nas with 10G

Thank you for your resolution. Thank you very much.
