### ISSUE TITLE
I still can't boot when I install more than 2 HDD

### ISSUE THREAD

**Issue by vinhnguyen1104** [fbelavenuto/arpl-modules#167]
I still can't boot when I install more than 2 HDD with 10th and 11th generation CPU. With lower generation CPU, boot normally.

**Comment by fbelavenuto** [comment]
You are selected LKM in "prod" option?

**Comment by vinhnguyen1104** [comment]
> 



> > LKM, I choose "dev".
> 
> Then change to prod and test

Thank you  ! I chose prod and booted normally.
