### ISSUE TITLE
Please add support for network card JMC250 PCI Express Gigabit Ethernet Controller

### ISSUE THREAD

**Issue by adixus** [fbelavenuto/arpl-modules#168]
Please...help....When I configure the Loader, the network card gives me IP and after I start the Synology it doesn't give me IP anymore. If I use a network card on the USB it assigns me IP. I am using an asus x52je laptop. Thx!!!

![20230128_154343](https://user-images.githubusercontent.com/78258279/215334364-ca4c7d62-9d2e-4e72-aaff-ba189e06bd08.jpg)
![20230128_160531](https://user-images.githubusercontent.com/78258279/215334366-9da96f96-1f43-4790-b494-a429867db250.jpg)

**Comment by fbelavenuto** [comment]
Ok, I'll compile this driver for DSM, please wait a little

**Comment by fbelavenuto** [comment]
Please, update modules, rebuild and test it.

**Comment by fbelavenuto** [comment]
https://github.com/fbelavenuto/arpl/wiki/Update-ARPL

**Comment by adixus** [comment]
I updated the modules and now it won't start. I've been waiting 10 minutes for it to appear in Synology Assistant and it still hasn't. I mention that I have arpl v1.0-beta9 and I have updated the modules.

**Comment by fbelavenuto** [comment]
Go to loader, advanced menu, modules, select all modules, rebuild and test

**Comment by adixus** [comment]
It worked. Thanks for your time and you deserve a cold beer. :) You're the best!
