### ISSUE TITLE
iavf driver missing

### ISSUE THREAD

**Issue by terrytw** [fbelavenuto/arpl-modules#173]
Hi devs, thanks for this great project!
I have encountered a problem, where during build I saw that iavf (and igbvf, ixgbevf series of virtual function modules) was included by default. But after building and installation, I saw that in /lib/modules, there is no iavf.ko (or any of the virtual function modules).

Is it a bug? Or am I missing something here?

**Comment by christaikobo** [comment]
Stale project.
