### ISSUE TITLE
atlantic AQC107 frequently down

### ISSUE THREAD

**Issue by Cryental** [fbelavenuto/arpl-modules#28]
Hello.
I'm using 10gbps pcie card but it's frequently down when booted and passed 5 min. I tried to change motherboard and card but same problem is happening. Can you please look at this problem once?

0000:01:00.0 Ethernet controller: Aquantia Corp. AQC107 NBase-T/IEEE 802.3bz Ethernet Controller [AQtion] (rev 02)
        Subsystem: Aquantia Corp. Device 0001
        Kernel driver in use: atlantic

**Comment by fbelavenuto** [comment]
Please update modules, rebuild the loader and test it.

**Comment by Cryental** [comment]
I will test today and let you know :)

**Comment by Cryental** [comment]
I'm running iperf3 for 1 hour with maximum speed and seems no problem. I will test more hours and tell you final :)

**Comment by Cryental** [comment]
![0A1010D3-3094-4B85-BA19-9D8202A035B2](https://user-images.githubusercontent.com/44664655/191511542-6e9c1e55-75a1-4543-8803-5b8c3d22b684.png)

No problem so far, good work 👍 I will monitor few days.

**Comment by Cryental** [comment]
Seems bug is fixed now, thank you for your work!

**Comment by Cryental** [comment]
Sorry, reopening this issue because I'm experiencing the same issue again after running for about 17 hours.

`17:40:43 up  6:20,  1 user,  load average: 0.29, 0.46, 0.53 [IO: 0.15, 0.16, 0.13 CPU: 0.14, 0.29, 0.36]`

I can see the driver is recognized by DSM still, but it's disconnected actually.

```
0000:01:00.0 Ethernet controller: Aquantia Corp. AQC107 NBase-T/IEEE 802.3bz Ethernet Controller [AQtion] (rev 02)
	Subsystem: Device 7053:1001
	Kernel driver in use: atlantic
```

![image](https://user-images.githubusercontent.com/44664655/191953030-18f78f6f-76a7-4084-b3d9-351b56c30909.png)

I tried to reconnect the cable, no response. Can you please look at it once? Thank you!

**Comment by Cryental** [comment]
Seems the driver doesn't work with the latest version, it won't recognize the kernel driver:

```
0000:01:00.0 Ethernet controller [0200]: Aquantia Corp. AQC107 NBase-T/IEEE 802.3bz Ethernet Controller [AQtion] [1d6a:07b1] (rev 02)
        Subsystem: Aquantia Corp. Device [1d6a:0001]
````

I tried to load the driver manually with insmod from https://github.com/fbelavenuto/arpl-modules/commit/f370756b5db563ce31cbc849f0f07457806784e4, and it loaded and works normally (not sure if it will down again).

**Comment by fbelavenuto** [comment]
Weird! I didn't change anything in the modules from version 10 to 11!
Did you update the ARPL through the menu or rewrite the flash drive?

**Comment by Cryental** [comment]
I have reinstalled the DSM to check, and the new atlantic driver which you compiled for the latest version doesn't load to DS918+ system. Can you please try to recompile with latest driver? https://github.com/Aquantia/AQtion

**Comment by Cryental** [comment]
Thank you :) I will wait >.<

**Comment by fbelavenuto** [comment]
Please update modules, rebuild the loader and test it

**Comment by Cryental** [comment]
```
0000:01:00.0 Ethernet controller [0200]: Aquantia Corp. AQC107 NBase-T/IEEE 802.3bz Ethernet Controller [AQtion] [1d6a:07b1] (rev 02)
	Subsystem: Aquantia Corp. Device [1d6a:0001]
	Kernel driver in use: atlantic
```

Seems working! I will test few days and tell you if it's working great :)
