### ISSUE TITLE
Network Module 

### ISSUE THREAD

**Issue by agisofttm** [fbelavenuto/arpl-modules#34]
Hi @fbelavenuto ,

Is there igc module for arpl?
I've a shitty Intel I225 integrated card in MiniPC with J4125 processor, and I can successfuly boot into boot loader, but after than I can't boot the kernel. This is lspci output 

`Intel Corporation Device [8086:15f3]`

Thank you

**Comment by fbelavenuto** [comment]
Bad news! The igc driver do not compile in actual DSM kernel version.
https://xpenology.com/forum/topic/62857-b660-i-build-please-add-intel-igc-network-25gb-drivers-to-httpsgithubcompocopicorp-ext-repo/

**Comment by agisofttm** [comment]
> Bad news! The igc driver do not compile in actual DSM kernel version.
> https://xpenology.com/forum/topic/62857-b660-i-build-please-add-intel-igc-network-25gb-drivers-to-httpsgithubcompocopicorp-ext-repo/

Yap I assumed it would be a problem with those drivers. Now I also tried with USB 3 Netowk Adapter ASIX AX88179 - I can boot into the loader, but after compile, again cannot boot the Kernel. Can you check this as well, because you have it in modules. 

Thanks again and sorry for disturbing you

**Comment by fbelavenuto** [comment]
Please go to loader/update menu and update the modules, rebuild the loader and boot it. Test if your USB network adapter works.

**Comment by agisofttm** [comment]
> Please go to loader/update menu and update the modules, rebuild the loader and boot it. Test if your USB network adapter works.

Ok - thanks - I'll do it immediately

**Comment by agisofttm** [comment]
@fbelavenuto Everything working flawlessly - Thank you again - you are amazing 👍
