### ISSUE TITLE
Add Intel i225/i226 igc driver

### ISSUE THREAD

**Issue by jim3ma** [fbelavenuto/arpl-modules#51]
I have backport `igc` driver from linux 5.12, primary functions is working.
Now we can add igc driver in arpl.
Source: https://github.com/jim3ma/synology-igc

**Comment by darkgetter** [comment]
> > @jim3ma hi, jim, would you please try to backport i915 driver of 10th gen CPU to ds920? thanks
> 
> I have took a look the i915 in mainline kernel. We need to backport `drm`, `drm_kms_helper` and `i915` at least, this will be a long time to do.

thanks for your reply, i tried one posted on xpenology forum --> #44 
but null exception is thrown...
無論如何，非常感謝！（thank you very much）
