### ISSUE TITLE
ARPL 1.0 beta ixgbe driver crashed all devices with this network adapter intel 520 0.5 aplha 1 all was fine

### ISSUE THREAD

**Issue by nemesis122** [fbelavenuto/arpl-modules#55]
[log.pdf](https://github.com/fbelavenuto/arpl/files/9900222/log.pdf)

**Comment by nemesis122** [comment]
thank you very much i will try and let you know

**Comment by nemesis122** [comment]
enjoy the littel money thank you for your great loader and the support :-)

**Comment by nemesis122** [comment]
Hi Fabio 
i have now rebuilt the loader (means i have downloaded the img. again but the same issue is happen so i have to update the modules again in this case in the next release the ixxgbe driver is solved without update the modules ?

Other Question Direct boot means he bootet directly the loader and patch it with the drivers ?
thank you and have a nice day 
Michael

**Comment by nemesis122** [comment]
update the modules all is working perfect for me this is fine with the next arpl release i hope is fixed with updatest the modules when the loader is created .
thank you 
Michael

**Comment by fabio-ffclrp** [comment]
Hi, thanks for the sponsor! In the next release of ARPL the new modules will be embedded.
