### ISSUE TITLE
Can you add Intel igc driver(I225/226) network card driver?

### ISSUE THREAD

**Issue by MadGhostcn** [fbelavenuto/arpl-modules#60]
Hello, developer.
[jim3ma](https://github.com/jim3ma)has Backport from Linux Kernel v5.12.
https://github.com/jim3ma/synology-igc

**Comment by pdttinh** [comment]
I looked on intel.com and found out that this i225v card has a driver error, intel has released a new update on windows but I don't know if it's available on linux.

https://www.intel.com/content/www/us/en/support/articles/000057261/ethernet-products/gigabit-ethernet-controllers-up-to-2-5gbe.html

**Comment by fbelavenuto** [comment]
#59
