### ISSUE TITLE
Please update igc to 1.3.0

### ISSUE THREAD

**Issue by CoderKe** [fbelavenuto/arpl-modules#83]
The version fixes memory leak in all previous versions, please upgrade to this version ASAP.

**Comment by fbelavenuto** [comment]
Hi, igc has already been updated to this version:
https://github.com/fbelavenuto/arpl-modules/pull/78

**Comment by CoderKe** [comment]
[v1.0-beta6](https://github.com/fbelavenuto/arpl/releases/tag/v1.0-beta6)
This version has updated igc to 1.3.0, right?

**Comment by CoderKe** [comment]
Thank you very much！
